name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2) Build & push
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true                   # ← enable push
          tags: jun332/jun_131:master  # ← your repo/image name