name: test-suite

on:
  workflow_call:

jobs:
  codeql-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: typescript

      - name: Build files for CodeQL
        run: |
          npm install
          npm run build || true

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  touca-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Debug Python Environment
      run: |
        python --version
        python -m pip --version

    - name: Install TryTouca with Debugging
      run: |
        python -m pip install --upgrade pip
        pip install trytouca --verbose || true

    - name: Install TryTouca from GitHub (Fallback)
      if: failure()
      run: |
        python -m pip install git+https://github.com/trytouca/trytouca-python.git

    - name: Create Virtual Environment (Fallback)
      if: failure()
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install trytouca


  testlink:
    runs-on: ubuntu-latest

    steps:
      - name: Clone TestLink Repository
        run: |
          git clone https://github.com/TestLinkOpenSourceTRMS/testlink-code.git
          cd testlink-code

      - name: Set up environment for TestLink
        run: |
          sudo apt-get update
          sudo apt-get install -y php mysql-server apache2
          # Additional setup for TestLink dependencies if required

      - name: Run TestLink Setup
        run: |
          cd testlink-code
          # Example: Run tests or start TestLink
          # php testlink-cli.php --run-tests